[platformio]
default_envs = BOARD_WAVESHARE_ESP32_S3_TOUCH_LCD_7

; ---- Zajednike opcije za sve envove ----
[env]
framework = arduino
; pioarduino platforma (Arduino esp32 3.x, ne treba Git)
platform = https://github.com/pioarduino/platform-espressif32/releases/download/53.03.11/platform-espressif32.zip
monitor_speed = 115200
upload_port = COM5
monitor_port = COM5
monitor_filters = esp32_exception_decoder
lib_deps =
    https://github.com/esp-arduino-libs/ESP32_Display_Panel/archive/refs/heads/master.zip
    https://github.com/esp-arduino-libs/ESP32_IO_Expander/archive/refs/tags/v1.1.0.zip
    https://github.com/esp-arduino-libs/esp-lib-utils/archive/refs/tags/v0.2.0.zip
    lvgl/lvgl@^8.4.0
    bblanchon/ArduinoJson@^7.0.0

; ---- Build flags zajednicki ----
[common]
build_flags =
    -DCORE_DEBUG_LEVEL=1
    -DLV_CONF_INCLUDE_SIMPLE
    -DLV_LVGL_H_INCLUDE_SIMPLE
    -I src

; ---- RGB/MIPI-DSI LCD (no color swap) ----
[rgb_lcd]
build_flags =
    -DLV_COLOR_16_SWAP=0

; ---- Waveshare ESP32-S3-Touch-LCD-7 ----
[env:BOARD_WAVESHARE_ESP32_S3_TOUCH_LCD_7]
build_flags =
    ${common.build_flags}
    ${rgb_lcd.build_flags}
    -DESP_PANEL_BOARD_DEFAULT_USE_SUPPORTED=1
    -DBOARD_WAVESHARE_ESP32_S3_TOUCH_LCD_7
board = BOARD_WAVESHARE_ESP32_S3_TOUCH_LCD_7
